### ISSUE TITLE
Release composer package?

### ISSUE THREAD

**Issue by afk11** [reactphp/filesystem#10]
Just noticed this doesn't have a tagged release yet, so it can't be included in packages marked stable!

**Comment by WyriHaximus** [comment]
Currently working on a child process adapter so there is no need to require the EIO extension on install once that is done. This is one of the last few things before tagging a release.

**Comment by aedart** [comment]
How long before this package is released?

**Comment by aedart** [comment]
How long before this package is released in a stable version, e.g. a version 1?

**Comment by WyriHaximus** [comment]
Just posted the roadmap for this package ultimately leading to version `v1.0.0` at https://github.com/reactphp/filesystem/issues/13
