### ISSUE TITLE
ChildProcessAdapter cannot read/write binary files

### ISSUE THREAD

**Issue by jmoo** [reactphp/filesystem#38]
This is caused by ```WyriHaximus/reactphp-child-process-messenger``` use of json_encode/json_decode which does not support binary strings.

I'd make a pull request but I'm not sure if this should be fixed here by (probably base64) encoding the payloads or if it should be fixed in ```WyriHaximus/reactphp-child-process-messenger``` by moving to a binary format for rpc 

Example:
```php
$loop = \React\EventLoop\Factory::create();
$filesystem = \React\Filesystem\Filesystem::create($loop);

$contents = base64_decode('UEsDBAoAAAAAAEw400'); // start of zip header
$filename = sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'bin.data';

echo 'Using ', get_class($filesystem->getAdapter()), PHP_EOL;
$filesystem->file($filename)->putContents($contents)->then(function ($contents) use ($filename) {
    echo file_get_contents($filename), PHP_EOL;
}, function (Exception $e) {
    echo $e->getMessage(), PHP_EOL;
    echo $e->getTraceAsString(), PHP_EOL;
});

$loop->run();
```

**Comment by WyriHaximus** [comment]
Yeah that makes sense, haven't had time yet with the 1.0 releases earlier this week. But will have a go at it tonight 👍

**Comment by WyriHaximus** [comment]
FYI #39 is up fixing this issue
