### ISSUE TITLE
Support for other types of filesystems

### ISSUE THREAD

**Issue by F21** [reactphp/filesystem#4]
It would be really awesome if we can use the library against things like S3, ceph or some other type of file system.

I noticed that flysystem will not be supporting async (https://github.com/thephpleague/flysystem/issues/198), so I think the idea of having built in adapters for filesystems other than EIO would be nice.

**Comment by WyriHaximus** [comment]
When someone writes an adapter for it you can do that. Specifically wrote an [interface](https://github.com/reactphp/filesystem/blob/master/src/AdapterInterface.php) for that. The [filesystem class](https://github.com/reactphp/filesystem/blob/30064df30ba74269627d1b972107bea57432c351/src/Filesystem.php#L18-L22) of course supports it so you can inject another one in. ([Going to give S3 a shot myself.](https://github.com/WyriHaximus/reactphp-filesystem-s3))

The plan is to get libuv support in as well. But the main focus will be on local filesystems. However with the adapter interface you could create S3/Dropbox/FTP etc etc ones. And I see more in community packages then jamming them all in this core package. (Also want to keep it clean.)

**Comment by WyriHaximus** [comment]
P.S. Don't see this close as a rejection of the idea. I would love to see that happen but the focus will be on local filesystem for now. It would be beyond awesome to do something like this:

```php
<?php

$loop = Factory::create();
Filesystem::create($loop)->dir('/local/path/to/data/')->mirror(Filesystem::create($loop, new S3Adapter($loop))->dir('bucker://s3bucketname/'));

$loop->run();
```
