### ISSUE TITLE
Putting all adapters in their own repositories

### ISSUE THREAD

**Issue by WyriHaximus** [reactphp/filesystem#47]
One of the things I have been thinking about for `v0.2` is pulling all adapters out of this repository and putting them child process one under `reactphp` and others either under `reactphp` and/or `friends-of-reactphp`.

Pros:
* Each adapter can set it's own required extensions needed for it to function
* Stimulates a ecosystem of adapters by leading the way
* Each adapter can be developed/maintained at it's own pace and has it's own releases without blocking this repository
* Users can require only what they need for their environment

Cons:
* Each adapter can set it's own required extensions needed for it to function
* Users might not know what they need for the best performance for their environment and when not including/requiring all adapters they might miss out on that better performance.

What are your opinions about this @clue, @jsor, and @cboden?

**Comment by clue** [comment]
My vote is: batteries included, but swappable.

It's my understanding that this project should fulfill the 80% use case without requiring any additional repositories. For people that have special requirements, they can still rely on the interfaces exposed and use a custom/special implementation. This is in line with how the EventLoop component provides implementations for common extensions and still allows consumers to use experimental extensions by implementing the `LoopInterface` themselves.

Unlike the Cache component, I don't see us ever ending up with dozens of possible implementations. Should this turn out to happen in the future, we can still do a split then.

**Comment by jsor** [comment]
What @clue said 👍

**Comment by WyriHaximus** [comment]
Agreed 👍
