### ISSUE TITLE
Create ext-uv adapter

### ISSUE THREAD

**Issue by WyriHaximus** [reactphp/filesystem#60]
With `ext-uv` event loop merged into `react/event-loop` (via https://github.com/reactphp/event-loop/pull/112) this opens the door to an `ext-uv` filesystem adapter. I've already started working on it and will open a PR as soon as I have something to share.

**Comment by CharlotteDunois** [comment]
Dup of #9? :D

**Comment by WyriHaximus** [comment]
Yes, my bad!
