### ISSUE TITLE
not supported in windows machine

### ISSUE THREAD

**Issue by itisjoby** [reactphp/filesystem#71]
while i got free time i decided to make a php code to do a scaning in my  directory using scandir().and loop it to find duplicates .if found any duplicates i wanted to move them to another folder.as this is a  time taking task and was freezing my pc for long time i decided to try react php.but while trying react php i faced so much trouble and later i found there are no adaptors on windows machines.i think i wasted a lot of time on this library and feel bad about trying it at the first place...

**Comment by clue** [comment]
@itisjoby I understand your frustration, but rest assured Windows support is something we're already working on: https://github.com/reactphp/filesystem/pull/64 should land soon and this should support Windows out of the box without any extensions.

I don't currently use this project on Windows, but it's my understanding it should have worked with the appropriate extension installed or should have given you an Exception to tell you about this?

Either way, thanks for letting us know, this should be resolved soon-ish :+1:
