### ISSUE TITLE
Move examples to a new markdown file or to `README.md`

### ISSUE THREAD

**Issue by Zizaco** [reactphp/filesystem#8]
The example code raise some "bad practice warnings" (which is understandable as the purpose of then is simply to illustrate the context of use). It would be nice to have an `examples.md` file that would explain and contain each of the examples.

See insight analysis:
https://insight.sensiolabs.com/projects/ce37859a-e3a3-42b5-8d97-455465dc5c6f/analyses/2

By doing this, we will be able to focus in fix/solve the more complicated issues raised by the Insight.

**edit:** I can send a PR on this if you wish (:

**Comment by WyriHaximus** [comment]
Honestly I see more value in update the examples with neatly formatted output. The examples are they so developers can easily try features out. (E.g. just run `php examples/directory_ls.php` and see what is does.) Also wouldn't it be easier to let insight ignore the examples directory? (Personally I use scrutinizer for my personal projects.)

**Comment by WyriHaximus** [comment]
Made some changes to the examples. The readme will also include a whole bunch of them so users can get started quickly :+1: .

P.S. https://insight.sensiolabs.com/help/excluding-files.html

**Comment by Zizaco** [comment]
Great. You are right!
I've added the `examples` to `global_exclude_dirs` and it went fine now.

I also use scrutinizer, but I find Insight more strict and detailed, also it gives those cool badges xD
[![SensioLabsInsight](https://insight.sensiolabs.com/projects/ce37859a-e3a3-42b5-8d97-455465dc5c6f/small.png)](https://insight.sensiolabs.com/projects/ce37859a-e3a3-42b5-8d97-455465dc5c6f)

**Comment by WyriHaximus** [comment]
Have to admit the insight badges looks pretty shiny. One of the neat things about scrutinizer is that you can completely tune their inspections: https://github.com/WyriHaximus/ReactGuzzleRing/blob/master/.scrutinizer.yml
