### ISSUE TITLE
Filesystem `exists()` file method stopped working with last child-process versions

### ISSUE THREAD

**Issue by mmoreram** [reactphp/filesystem#94]
Having this example

https://gist.github.com/mmoreram/6323b9bf536ba5346e5a26117512c208

Have different results when changing the `wyrihaximus/react-child-process-pool` dependency:

- Version `1.6.*` work properly in PHP7, composed doesn't update in PHP8
- Version `1.7.*` doesn't work in PHP7 and PHP8 due to compatibility class issues (we already know that issue), 
- Version `1.8.*` doesn't work in PHP7 nor in PHP8. The `exists()` method keeps waiting until the infinite in both PHP versions.

I don't know if some other methods are affected by this update.

**Comment by SimonFrings** [comment]
Hey @mmoreram, thanks for reporting this :+1:

Similar answer in here as in #95, this could be already obsolete with the rewrite of the project in #97. If this should still be a thing after the new version then we'll look further into this.

**Comment by clue** [comment]
@mmoreram Thanks for bringing this up! #97 has just been merged and I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:
